name: Deploy Online Access

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.repository != 'FrisSoftwareteam/Admin1' && github.repository != 'FrisSoftwareteam/Admin'
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Publish Access app
        run: dotnet publish Access/FirstReg.OnlineAccess.csproj -c Release -o publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B234BACDCB594A54A29AF901427DFA58 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3363559A40BB49CCA561AF45A8FE667E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5BB033CD81DF489DAAE80A8E2DC5F22D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "fr-access"
          slot-name: "Production"
          package: publish
