# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fr-access-admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.repository == 'FrisSoftwareteam/Admin'
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish Admin app
        run: |
          dotnet publish Admin/FirstReg.Admin.csproj -c Release -o publish-admin
          if (Test-Path publish-admin/appsettings.Development.json) {
            Remove-Item publish-admin/appsettings.Development.json
          }

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1EEFC0463B164E1DB5524D04C871717D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_68E8AE570D214B81B4C870B2A1300B5A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4F1C84DE9BDF444B9244D2D900BF951B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fr-access-admin'
          slot-name: 'Production'
          package: publish-admin
